import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import VideoEditorProvider from "@/contexts/videoEditorCtx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Video Editor",
  description: "Generated by create next app..",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <VideoEditorProvider>
        <body className={inter.className}>{children}</body>
      </VideoEditorProvider>
    </html>
  );
}
